component_depth: 1
languages:
- name: typescript
  production:
    exclude:
      - /acceptance/.*
      - /bin/.*
      - /docs/.*
      - /examples/.*
      - /fixtures/.*
      - /sandbox/.*
  test:
    include:
      - .*/__tests__/.*
